### PR TITLE
Upgrading Hippunfold to v1.2.0

### PR DESCRIPTION
**Pull request by akhanf**
We have a new release of hippunfold (v1.2.0), so I have adapted the v1.1.0 boutiques descriptor, and since it has now been published so I have updated the tool description within.

### CODE REVIEW

**Comment by prioux** [comment]
Excellent. I'll review this later today.

I think there might be boutiques fields for the citation and DOI, I'll look it up later.

**Comment by prioux** [comment]
@akhanf I will merge this immediately and then add the URL to the github page:

```json
  "url": "https://github.com/khanlab/hippunfold"
```

The boutiques spec contains two DOI fields: 'doi' is for the descriptor itself and 'tool-doi' is for the tool. Since your doi in the description is for a paper, I am not sure either of them is appropriate for it. So I will leave it there. Same for the citation, boutiques doesn't seem to have a citation section.

**Comment by prioux** [comment]
All done. Will be deployed in CBRAIN soon.

**Comment by akhanf** [comment]
Thank you!
________________________________

**Comment by prioux** [comment]
@akhanf : v1.2.0 is now installed in CBRAIN on 3 supercomputers.

**Pull request merged**
