### PR TITLE
Migrating fsl bet, fast, and first to Boutiques

### PR DESCRIPTION
**Pull request by ttaa9**
For #11. Also handles #6 and #57.

### CODE REVIEW

**Comment by prioux** [comment]
I am not sure I agree with removing the old version of FslBet ; unless it was really crummy and buggy, we should keep it around, and the new Boutique version be called something slightly different (e.g. FslBetB).

**Comment by ttaa9** [comment]
@prioux I don't mind that. I only removed it due to name clashes. Unless @glatard has any thoughts.

**Comment by glatard** [comment]
I think having two concurrent implementations of the same tool will be tricky in the long term. If a new tool name is introduced, we won't be able to remove any of these tools or the portal will crash. I'd rather remove the old one and make sure that the new one works well. If you go for the 2-tool solution, "FslBetB" is probably not a very good name as "B" won't make any sense to users.

**Comment by prioux** [comment]
Yeah, I suggested B for Boutique, but any other name would do too.

The thing is, if there are already tasks in CBRAIN for FslBet, and we switch the implementation to the Boutique version, then all the old tasks will crash when viewed/edited/restarted/recovered etc (I assume the content of the params hash is totally incompatible). That's why I suggested a different name. How nice do we want to be to existsing/past FslBet users?

**Comment by natacha-beck** [comment]
My opinion: 
- The new version of the tools (Boutique) should be the new one, it is better (more supported options, with extra validation) with the same name as previous (it will be less confusing for user in this way). 
- If we go with this solution, is it possible to continue to support the old task ? The params hash seems to be incompatible. Maybe we can imagine to do a migration and create a new FslBetOld to support this one. I'm not sure if it is possible and easy to do, finally is it worth it ?

**Comment by prioux** [comment]
We could manually 'adjust' old tasks to belong to a new class 'FslBetOld' like you suggest, but conceptually it's problematic: imagine that CBRAIN is deployed and used elsewhere, with some FslBet tasks already existing, it would break these other CBRAINs because they don't have that fix. And we can't create a migration in the CBRAIN platform code to adjust task classes that are defined in plugins, it makes no sense...

Now, obviously the new FslBet is better, so what do we call it?

**Comment by glatard** [comment]
What about Fsl-Bet or Bet-Fsl or just Bet with an "FSL" tag?

**Comment by natacha-beck** [comment]
I like the Bet version with an "fsl" tag. And for the old one we can maybe add a tag "Deprecated" or something like that to indicate which version to use to the user.

**Comment by prioux** [comment]
The tool can be named anything in CBRAIN; the Ruby class cannot.
So we could call the class FslBetV2 and let the admin name the tool
anything they want, including your suggestions.

**Comment by prioux** [comment]
The only thing being that by default, the class name is use to build a default name for the tool...

**Comment by ttaa9** [comment]
Ok, so the consensus is to put the old tools back with the original names, and then rename fsl_tool to tool?

**Comment by Najmahan** [comment]
I think, one FSL bet is sufficient. It is a lightweight process and users
can be informed that the old version does not exist, so they can rerun
their data with the new version if they must.

I suggest keeping the latest version only.

**Comment by Najmahan** [comment]
Can you gather information on how many BET tasks exist out there that might
run into this potential problem if the old tool is removed?

**Comment by prioux** [comment]
The pic belows reports that >1700 FslBet exist.

Pierre

[cid:058BFCD7-53B5-414D-A953-BEB42FF23291]
On Jul 27, 2016, at 16:37, Najmahan <notifications@github.com<mailto:notifications@github.com>> wrote:

Can you gather information on how many BET tasks exist out there that might
run into this potential problem if the old tool is removed?

**Comment by Najmahan** [comment]
Not sure where to see the picture. But I would say 1700 is nothing and I would still let the old BET Go. It is also a question of maintenance of two versions. It is more efficient to tell users to "please rerun with the new version".

**Comment by prioux** [comment]
Sorry, the message above was supposed to be a email message, not a GitHub comment. The email contained the pic...

**Comment by glatard** [comment]
So are we just removing the old tasks as @Najmahan suggested?

**Comment by prioux** [comment]
You can remove your own tasks if you want; I will not remove other user's tasks, I will archive them and wait for people to complain if they try to reactivate them!

By the way, this conversation is about the CBRAIN service and not really appropriate for GitHub... this should go on our Redmine project 'CBRAIN Service'.

**Comment by prioux** [comment]
@glatard @ttaa9 Is this ready to merge? I'm willing.

**Comment by ttaa9** [comment]
@prioux they work for me

**Comment by glatard** [comment]
I'm also ok to merge this. Now it's on @natacha-beck I guess.

**Pull request merged**
