### PR TITLE
Support large list of participants in BidsAppHandler

### PR DESCRIPTION
**Pull request by prioux**

### CODE REVIEW

**Comment by MontrealSergiy** [comment]
Hi, what bug this PR is targeting? goal there? Fix support for runs with all the participants or allow for arbitrary number of participants being selected?

**Comment by prioux** [comment]
Well, in the original design, when se;ecting a bids dataset. the user was provided with a table listing all the participants in it, with a checkbox for each of them. When you have 50 or 100 participants, it's possible the user will want ot run an analysis on just a subset (for testing or for creating statistical analysis with random subsets etc).

HOWEVER, we have encountered BIDS dataset with thousands of participants in them. The form was not only impossible to generate in reasoanle time, but also unreasonable to expect user to select or deselect the participants.

So now, when a BIDS dataset has more than 100 participants, the interface just says 'you are running on them all' and that's it.

**Comment by MontrealSergiy** [comment]
Could be a use case when user just test an idea / parameter choice on few participants or smth?
Greg says it how normal data scientist work. First do small study they scale it up

**Comment by MontrealSergiy** [comment]
May be for 100 + MS Word style of interface for page selection? a, c, d-x,

**Comment by prioux** [comment]
We don't really need more features. Users can create whatever bids subset they need before launching. This PR is to make sure the large ones are possible to launch. Please test it.

**Comment by prioux** [comment]
Also, feel free to change the two constants MAX_PARTICIPANTS_FOR_FORM and MAX_SUBTASKLIST_SIZE in `portal/bids_app_handler.rb` to trigger artificially the large content special code. I used 5 and 4 respectively on a 10 subject BIDS dataset for my own tests.

**Comment by MontrealSergiy** [comment]
I tried to test yet was not able to deploy the example bids app (from the spec ) as the bids app.

cbrain_plugins/bids_app_handler/cbrain_task_descriptors/exampebids.json

**Pull request merged**
