### PR TITLE
Deformation Simulation tool

### PR DESCRIPTION
**Pull request by MontrealSergiy**
What do you think of this tool?

### CODE REVIEW

**Comment by natacha-beck** [comment]
You can look at: 

https://github.com/aces/cbrain-plugins-neuro/blob/master/cbrain_task_descriptors/fmriprep_single_subject_20_1_3.json

for the status handling. 

You can put the cbrain-author too: 

```
    "custom": {
                "cbrain:readonly-input-files": true,
                "cbrain:author": "Natacha Beck &lt;natacha.beck@mcgill.ca&gt;"
            }
```

**Comment by MontrealSergiy** [comment]
Hi I replaced semicolon with double ampersand to improve error reporting

**Comment by prioux** [comment]
The return code of `deformation.pl` is hidden by your subsequence bash code. The command line must return THAT code to the framework, not the return code of the rest.

**Comment by MontrealSergiy** [comment]
Do you mean even after using && it still hides the failures?

> The return code of `deformation.pl` is hidden by your subsequent bash code. The command line must return THAT code to the framework, not the return code of the rest.

**Comment by natacha-beck** [comment]
Indeed since it is not your last command. CBRAIN handle the status of the latest executed command.

**Comment by MontrealSergiy** [comment]
> Indeed since it is not your last command. CBRAIN handle the status of the latest executed command.

This commands are not executed if the first one failed. Am I missing something? https://serverfault.com/a/373053

**Comment by prioux** [comment]
Possibly. If deformation succeeds but something else goes wrong... ? Which return code do we really need? (It's a question, I'm not sure)

Also, your code with the if is terribly convoluted because you're using a control structure (if..fi) as a command. Why not

```shell
... && test [DELTMP] == yes && rm -rf [OUTDIR]/TMP
```

Instead? It' much more straightforward.

**Comment by prioux** [comment]
And by the way, traditionally when testing a condition with a binary operator, we put the variable part of the operator first and the constant second. So

```
variable == 'yes'
```

instead of

```
'yes' == variable
```

It's much easier to understand.

**Comment by MontrealSergiy** [comment]
> Possibly. If deformation succeeds but something else goes wrong... ? Which return code do we really need? (It's a question, I'm not sure)
> 
> Also, your code with the if is terribly convoluted because you're using a control structure (if..fi) as a command. Why not
> 
> ```shell
> ... && test [DELTMP] == yes && rm -rf [OUTDIR]/TMP
> ```
> 
> Instead? It' much more straightforward.

`if` is more straighworward to me than &&, but do not mind test either.

If one part of pipeline failed, to me the whole pipeline failed. In other words  failure in copy or delete is still failure.

**Comment by natacha-beck** [comment]
Is it normal, that the descriptor don't have information about the container?

**Pull request merged**
